// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package relayer

import (
	"relayer_ton/api/relayer"
)

type ControllerV1 struct{}

func NewV1() relayer.IRelayerV1 {
	return &ControllerV1{}
}
